# Glayu Configuration

# Site
title: static site generator              # Site Title

# URL
permalink: categories/year/month/day/title  # Permalink format

# Directories
source_dir: source                          # Source folder
public_dir: public                          # Destination folder

# Theme
theme: glayu-docs                          # Selected Theme under themes dir
